### ISSUE TITLE
Image/Avatar scaling.

### ISSUE THREAD

**Issue by RickKraut** [phpBB-Studio/AdvancedPointsSystem#3]
**Is your feature request related to a problem? Please describe.**
Just a feature request, user image scaling/adjustment.

**Describe the solution you'd like**
the ability to set, or have a predetermined modifiable value to easily adjust user images on the overview page.

**Describe alternatives you've considered**
I noticed that, in the **aps_display.css** file at line **615** inserting a max-width and max-height into **".aps-col.s6"** achieves a similar effect, but also impacts the graphs that this extension provides lower in the page given default settings.

**Comment by mrgoldy** [comment]
I wouldn't suggest touching the `.aps-col` css's. That's the flexbox system that is responsive and is 'in charge' of the layout.

Moreover, I can see two "types of avatars" on the overview page.
The ones in the "top users" list and the ones in the "find a member & random user" blocks.
The ones in the top users list already have a fixed with.
`.aps-collection .aps-collection-item.aps-avatar img` line *526*
And if you want to scale/style the other ones, you can add a line like `.aps-panel .avatar { height: 100px; }`

Usually  the problem with having fixed heights and widths is responsiveness though.

**Comment by RickKraut** [comment]
I just thought it might be a feature some might request, as on the forums I run currently, users have a tendency to complain about the "restrictiveness" of the default avatar settings of phpbb.

thanks for the information though.
